import { LPCTemplate } from "@/lib/template-adapter";

export const mockLPCTemplates: LPCTemplate[] = [
  {
    id: "tpl-clinica-dental",
    name: "Clínica Dental Sorriso",
    description: "Landing page premium para clínicas dentárias com agendamento, serviços, depoimentos e contato.",
    category: "business",
    subcategory: "clinic",
    stack: "nextjs-tailwind",
    thumbnail_url: "/thumbnails/clinica-dental-sorriso.jpg",
    html: "<!-- LP Template: Clinica Dental Sorriso -->",
    css: "/* tailwind custom css */",
    js: "// interactivity",
    tags: "clinica dental, saude, landing page, agendamento",
    source: "manual",
    usage_count: 142,
    rating: 4.7,
    status: "available",
    price_stars: 120,
    price_suns: 0,
    price_moons: 0,
    original_price_stars: 150,
    created_by: "nexo-templates",
    created_at: "2026-05-10T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
    public_preview_token: "preview-clinica-dental-sorriso",
    metadata_json: {
      niche: "clinica dental",
      audience: "clínicas dentárias",
      difficulty: "beginner",
      style: "clean",
      colors: ["#FFFFFF", "#3B82F6", "#10B981"],
      features: ["Hero com CTA", "Seção de serviços", "Agendamento", "Depoimentos", "Formulário de contato"],
      useCases: ["Clínicas dentárias", "Consultórios médicos"],
      seoKeywords: ["clínica dental", "dentista", "landing page saúde"],
    },
  },
  {
    id: "tpl-restaurante-moderno",
    name: "Restaurante Moderno",
    description: "Site elegante para restaurantes com cardápio digital, reservas e galeria de pratos.",
    category: "business",
    subcategory: "restaurant",
    stack: "react-tailwind",
    thumbnail_url: "/thumbnails/restaurante-moderno.jpg",
    html: "<!-- LP Template: Restaurante Moderno -->",
    tags: "restaurante, comida, cardapio, reservas",
    source: "generated",
    usage_count: 89,
    rating: 4.5,
    status: "available",
    price_stars: 100,
    price_suns: 0,
    price_moons: 0,
    created_by: "community-chef",
    created_at: "2026-04-22T10:00:00Z",
    updated_at: "2026-06-10T12:00:00Z",
    public_preview_token: "preview-restaurante-moderno",
    metadata_json: {
      niche: "restaurante",
      audience: "restaurantes e bares",
      difficulty: "intermediate",
      style: "elegant",
      colors: ["#1F2937", "#F59E0B", "#FFFFFF"],
      features: ["Cardápio digital", "Reservas", "Galeria", "Depoimentos"],
      useCases: ["Restaurantes", "Bares", "Cafeterias"],
      seoKeywords: ["restaurante", "cardápio digital", "reservas"],
    },
  },
  {
    id: "tpl-saas-dashboard",
    name: "SaaS Dashboard Starter",
    description: "Dashboard SaaS completo com autenticação, sidebar, tabelas, charts e dark mode.",
    category: "saas",
    subcategory: "dashboard",
    stack: "nextjs-tailwind",
    thumbnail_url: "/thumbnails/saas-dashboard-starter.jpg",
    html: "<!-- LP Template: SaaS Dashboard -->",
    tags: "saas, dashboard, startup, admin",
    source: "manual",
    usage_count: 320,
    rating: 4.9,
    status: "available",
    price_stars: 250,
    price_suns: 10,
    price_moons: 0,
    created_by: "nexo-templates",
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-06-18T12:00:00Z",
    public_preview_token: "preview-saas-dashboard-starter",
    metadata_json: {
      niche: "saas dashboard",
      audience: "startups e SaaS",
      difficulty: "advanced",
      style: "modern",
      colors: ["#0F172A", "#3B82F6", "#FFFFFF"],
      features: ["Autenticação", "Sidebar", "Tabelas", "Charts", "Dark mode"],
      useCases: ["Startups SaaS", "Painéis administrativos"],
      seoKeywords: ["saas", "dashboard", "nextjs", "tailwind"],
    },
  },
  {
    id: "tpl-loja-sustentavel",
    name: "Loja Sustentável",
    description: "E-commerce minimalista para marcas sustentáveis com catálogo, carrinho e checkout.",
    category: "ecommerce",
    subcategory: "store",
    stack: "nextjs-shopify",
    thumbnail_url: "/thumbnails/loja-sustentavel.jpg",
    html: "<!-- LP Template: Loja Sustentavel -->",
    tags: "ecommerce, loja, sustentavel, moda",
    source: "generated",
    usage_count: 76,
    rating: 4.6,
    status: "unreviewed",
    price_stars: 180,
    price_suns: 0,
    price_moons: 0,
    created_by: "eco-designer",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-20T12:00:00Z",
    metadata_json: {
      niche: "ecommerce sustentável",
      audience: "marcas eco-friendly",
      difficulty: "intermediate",
      style: "minimal",
      colors: ["#F0FDF4", "#166534", "#FFFFFF"],
      features: ["Catálogo", "Carrinho", "Checkout", "Filtros"],
      useCases: ["Moda sustentável", "Produtos naturais"],
      seoKeywords: ["ecommerce", "loja sustentável", "shopify"],
    },
  },
  {
    id: "tpl-portfolio-fotografo",
    name: "Portfolio Fotógrafo",
    description: "Portfolio visual para fotógrafos com galeria em masonry, sobre e formulário de contato.",
    category: "portfolio",
    subcategory: "photographer",
    stack: "react-tailwind",
    thumbnail_url: "/thumbnails/portfolio-fotografo.jpg",
    html: "<!-- LP Template: Portfolio Fotografo -->",
    tags: "portfolio, fotografo, galeria, criativo",
    source: "manual",
    usage_count: 210,
    rating: 4.8,
    status: "available",
    price_stars: 80,
    price_suns: 0,
    price_moons: 0,
    created_by: "creative-studio",
    created_at: "2026-02-14T10:00:00Z",
    updated_at: "2026-05-30T12:00:00Z",
    public_preview_token: "preview-portfolio-fotografo",
    metadata_json: {
      niche: "portfolio fotográfico",
      audience: "fotógrafos e criativos",
      difficulty: "beginner",
      style: "visual",
      colors: ["#000000", "#FFFFFF", "#F59E0B"],
      features: ["Galeria masonry", "Sobre", "Contato", "Lightbox"],
      useCases: ["Fotógrafos", "Artistas visuais"],
      seoKeywords: ["portfolio", "fotógrafo", "galeria"],
    },
  },
];
